templates:
  global:
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      www.tokyotosho.info: 5 seconds
      nyaa.si: 5 seconds
      acgnx.se: 5 seconds
      tracker.minglong.org: 5 seconds
      horriblesubs.info: 5 seconds
      www.anirena.com: 5 seconds
      feed.animetosho.org: 5 seconds
      ru.erai-raws.info: 5 seconds
      www.shanaproject.com: 5 seconds
      anidex.info: 5 seconds

  anime_regexp:
    accept_all: yes
    convert_magnet: # Because the content_filter filter only works on torrents
      timeout: 240 seconds
    regexp:
      reject:
        - '\[FA\]' # German Subs
        - '\[FS\]' # Spanish Subs (Hard Sub even)
        - '\[RoFL\]' # German Subs
        - '\[PM\]' # German Subs
        - '\[AAF\]' # Spanish Subs
        - '\[IDIF\]' # Spanish Subs
        - '\[INDO SUB\]' # Non-English Subs
        - '\[PuyaSubs\!\]' # Spanish Subs
        - '\[FrozenFruitSubs\]' # Russian Subs
        - '\[SakuraCircle\]' # Mainly Hentai
        - '\[hikiko123\]' # Hentai
        - '\[JustBLThings-aarinfantasy\]' # Not into BL things
        - '\[HYSUB\]' # Not Subtitled in English (Hardsub of ... Not English) Subs
        - '\[THSUB\]' # Not Subtitled in English (Hardsub of ... Not English) Subs
        - '\[Ohys-Raws\]' # No Subtitle Raws (actual Raws)
        - '\[MSK-Raws\]' # No Subtitle Raws (actual Raws)
        - '\[Anime Time\]' # Hard Subs suck, and it's easy to forget to check the hard sub box when adding to AniDB which makes them waste time (and get annoyed)
        - '\[DVD\]' # Usually means ISO Release
        - '(\[English Dub\])' # I don't want English Dubs
        - "FuniDub" # I don't want English Dubs
        - "Dub" # I don't want English Dubs (which in theory all dubs with these feeds are english)
        - "DVD5" # Usually means ISO Release
        - "DVD-Rip" # Usually means ISO Release
        - "DVD_ISO" # Usually means ISO Release
        - "Hentai" # ugh, no
        - "[Pp]orn" # God... why are you posting that to an ANIME feed..
        - "JulyJailbait" # God... why are you posting that to an ANIME feed.. but at least you give me something to filter on..
        - '\[BDMV\]' # Usually means ISO Release
        - "DVDISO" # Usually means ISO Release
        - "COSPLAY" # I just want video (tho sometimes this stuff is quite good)
        - "arabic" # English please
        - "English Dubbed" # I don't want English Dubs
        - "(Dual[- ]Audio)": # I don't want English Dubs
            not:
              - "KOR" # Except sometimes I guess it's Japaneese and KOREAN (vs JPN & ENG)
        - '\.zip' # At some point work on moving this to just regex vs file contents, as title/description sometimes produces false positives
        - '\.rar' # At some point work on moving this to just regex vs file contents, as title/description sometimes produces false positives
        - "Drama CD" # I just want video
        - "Eng-Dub" # I don't want English Dubs
        - "1080p": # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
              - "(AV1|HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size - but... it looks like this allows for stuff that should be rejected to pass..damn it.
              - '\[SSA\]' # Seems some groups are using HEVC etc .. but not mentioning it
        - "1920x1080": # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
              - "(AV1|HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size
        - "UHD": # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
              - "(AV1|HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size
        - "2160p": # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
              - "(AV1|HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size
        - '-NanDesuKa': # Downloaded directly from their RSS, this is so I don't get other resolutions from them
            not:
              - "(HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size
        - '\[SSA\]': # Downloaded directly from their RSS, this is so I don't get other resolutions from them
            not:
              - "(1080p)" # But if they say it's HEVX/x265, it might be a sane file size
        - '\[erai-raws\]': # Downloaded directly from their RSS, this is so I don't get other resolutions from them
            not:
              - "(HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size
        - '\[SubsPlease\]': # Downloaded directly from their RSS, this is so I don't get other resolutions from them
            not:
              - "(HEVC|x265|H265|H.265)" # But if they say it's HEVX/x265, it might be a sane file size
      from: 
      - category
      - title
    content_filter:
      reject:
        - "*.ISO"
        - "*-ISO"
        - "*.iso"
        - "*-iso"
        - "*.img"
        - "*-img"
        - "*.exe"
        - "*.EXE"
        - "*.msi"
        - "*.MSI"

  download-deluge:
    deluge:
      path: /home/user/Downloads
      #move_completed_path:  /home/user/Downloads/finished # Handled by movefinished.yaml now
      label: anime
      ratio: 1.5
      remove_at_ratio: yes
      magnetization_timeout: 30

  bravesail-rename:
    manipulate:
      - title:
          replace:
            regexp: '^(\[.*\])((.*(?=[฀-﫿]).+?)?(\s{1,3}\/\s)|(\s+\(.*(?=\/)\/\s))'
            format: '\1 '
      - title:
          replace:
            regexp: ':'
            format: ''
    set:
      content_filename:  '{{title}}'

  animeerairaws:
    accept_all: yes
    #magnets: no # Because the content_size filter only works on torrents
    convert_magnet: # Because the content_size filter only works on torrents
      timeout: 240 seconds
    content_size:
      max: 900
      strict: yes
    quality: 1080p

  anime1080p:
    accept_all: yes
    #magnets: no # Because the content_size filter only works on torrents
    convert_magnet: # Because the content_size filter only works on torrents
      timeout: 240 seconds
    quality: 1080p

tasks:
  # Formally NC-RAWS
  animedl-bravesail: 
    rss:
      url: https://nyaa.si/?page=rss&c=1_2&f=0&u=BraveSail
      ascii: yes
      all_entries: no
    template: 
      - anime_regexp
      - bravesail-rename
      - download-deluge
  # Exception to the Rule on no H264/AVC, as they usually only release in AVC
  animedl-taleOfHerdingGods: 
    rss:
      url: https://nyaa.si/?page=rss&q=%5BFSP+DN%5D+tales+of+herding&c=0_0&f=0
      ascii: yes
      all_entries: no
    template: 
      - anime1080p
      - download-deluge 
  animedl-erairaws:
    rss:
      url: https://nyaa.si/?page=rss&c=1_2&f=0&u=erai-raws
      ascii: yes
      all_entries: no
    template: 
      - animeerairaws
      - download-deluge          
  animedl-nyaa:
    rss:
      url: https://nyaa.si/?page=rss&c=1_2&f=0
      ascii: yes
      all_entries: no
    template: 
      - anime_regexp
      - download-deluge 
  animedl-shanaproject:
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
      accept-encoding: "gzip, deflate, br"
      accept-language: "en-US,en;q=0.9"
      cookie: "__ddgid_=3Qvwc4J3kyTI8AHy; __ddg2_=UAmMGAi25vdjubuB; __ddg1_=gIL8bO82aApP6ufFnisO" #This looks to be the key
    rss:
      url: https://www.shanaproject.com/feeds/site/
      ascii: yes
      all_entries: no
    cfscraper: yes  
    template: 
      - anime_regexp
      - download-deluge 
  animedl-animetosho:
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
      accept-encoding: "gzip, deflate, br"
      accept-language: "en-US,en;q=0.9"
      cookie: "__ddgid_=3Qvwc4J3kyTI8AHy; __ddg2_=UAmMGAi25vdjubuB; __ddg1_=gIL8bO82aApP6ufFnisO" #This looks to be the key
    rss:
      url: https://feed.animetosho.org/rss2?only_tor=1
      ascii: yes
      all_entries: no
    cfscraper: yes
    template: 
      - anime_regexp
      - download-deluge 
  animedl-tokyotosho:
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
      accept-encoding: "gzip, deflate, br"
      accept-language: "en-US,en;q=0.9"
      cookie: "__ddgid_=3Qvwc4J3kyTI8AHy; __ddg2_=UAmMGAi25vdjubuB; __ddg1_=gIL8bO82aApP6ufFnisO" #This looks to be the key
    rss:
      url: https://www.tokyotosho.info/rss.php?filter=1
      ascii: yes
      all_entries: no
    cfscraper: yes
    template: 
      - anime_regexp
      - download-deluge 
  animedl-acgnx:
    rss:
      url: https://www.acgnx.se/rss-sort-2.xml
      ascii: yes
      all_entries: no
    template: 
      - anime_regexp
      - download-deluge 
  # Unfortunately prone for Henti/Porn/Warez that can be difficult to filter out
  # animedl-anidex:
  #   headers:
  #     User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
  #     accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
  #     accept-encoding: "gzip, deflate, br"
  #     accept-language: "en-US,en;q=0.9"
  #     cookie: "__ddgid_=3Qvwc4J3kyTI8AHy; __ddg2_=UAmMGAi25vdjubuB; __ddg1_=gIL8bO82aApP6ufFnisO" #This looks to be the key
  #   cfscraper: yes
  #   rss:
  #     url: https://anidex.info/rss/?cat=1&lang_id=1&group=0&q=&h=0
  #     # Web equiv: https://anidex.info/?page=search&id=1&lang_id=1&group_id=0&q=
  #     ascii: yes
  #     all_entries: no
  #   template: 
  #     - anime_regexp
  #     - download-deluge 
  # This is done primarily as a task to get data from deluge because content_size doesn't work on magnets well during initial filtering
  pause_large_torrents:
    sleep:
      seconds: 60 # This should give enough time for most of the torrents/magnets to start and get sizes etc.
    from_deluge: yes
    disable: [seen, seen_info_hash]
    # Pause all torrents larger then 30GB that do not have the label "largeanimeok", Note Deluge labels are always lowercase in flexget
    # And I don't want to deal with some of the stupidly large torrents people post that I either end up downloading (and then deleting)
    # or chew up my Seedbox bandwith
    if:
      # - content_size >= 30720: accept
      # 2023/01/31 - For some reason deluge_label isn't available
      # 2025/04/05 - For some reason content_size is now in bytes not MB
      - deluge_label != "largeanimeok" and content_size >= 32212254720: accept 
    deluge:
      action: pause

schedules:
  - tasks: "*"
    interval:
      hours: 1
      jitter: 120