templates:
  global:
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      www.tokyotosho.info: 5 seconds
      nyaa.si: 5 seconds
      acgnx.se: 5 seconds
      tracker.minglong.org: 5 seconds
      horriblesubs.info: 5 seconds
      www.anirena.com: 5 seconds
      feed.animetosho.org: 5 seconds
      ru.erai-raws.info: 5 seconds

  anime_regexp:
    accept_all: yes
    regexp:
      reject:
        - '\[FA\]' # German Subs
        - '\[RoFL\]'  # German Subs
        - '\[PM\]' # German Subs
        - '\[FrozenFruitSubs\]'  # Russian Subs
        - '\[Anime Time\]' # Hard Subs suck, and it's easy to forget to check the hard sub box when adding to AniDB which makes them waste time (and get annoyed)
        - '\[erai-raws\]' # Downloaded directly from their RSS, this is so I don't get other resolutions from them
        - '\[DVD\]' # Usually means ISO Release
        - '(\[English Dub\])' # I don't want English Dubs
        - 'FuniDub' # I don't want English Dubs
        - 'Dub' # I don't want English Dubs (which in theory all dubs with these feeds are english)
        - 'DVD5' # Usually means ISO Release
        - 'DVD-Rip' # Usually means ISO Release
        - 'Hentai' # ugh, no
        - '[Pp]orn' # God... why are you posting that to an ANIME feed..
        - 'JulyJailbait' # God... why are you posting that to an ANIME feed.. but at least you give me something to filter on..
        - '\[BDMV\]' # Usually means ISO Release
        - 'DVDISO' # Usually means ISO Release
        - 'COSPLAY' # I just want video (tho sometimes this stuff is quite good)
        - 'arabic' # English please
        - 'English Dubbed' # I don't want English Dubs
        - '(Dual[- ]Audio)': # I don't want English Dubs
            not:
            - 'KOR' # Except sometimes I guess it's Japaneese and KOREAN (vs JPN & ENG)
        - '\.zip' # At some point work on moving this to just regex vs file contents, as title/description sometimes produces false positives
        - '\.rar' # At some point work on moving this to just regex vs file contents, as title/description sometimes produces false positives
        - 'Drama CD' # I just want video
        - 'Eng-Dub' # I don't want English Dubs
        - '360p'
            not: #Stupid yaml, from how the docs look this is the wrong identation, but it works this way ..
            - '(DVD)'
        - '480p'
            not: #Stupid yaml, from how the docs look this is the wrong identation, but it works this way ..
            - '(DVD)'
        - '1080p': # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not: #Stupid yaml, from how the docs look this is the wrong identation, but it works this way ..
            - '(HEVC|x265|H265|H.265)'  # But if they say it's HEVX/x265, it might be a sane file size - but... it looks like this allows for stuff that should be rejected to pass..damn it.
        - '1920x1080': # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
            - '(HEVC|x265|H265|H.265)' # But if they say it's HEVX/x265, it might be a sane file size
        - 'UHD': # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
            - '(HEVC|x265|H265|H.265)' # But if they say it's HEVX/x265, it might be a sane file size
        - '2160p': # Just 720p for now until my main release groups understand how to release sane HEVC/x265 file sizes
            not:
            - '(HEVC|x265|H265|H.265)' # But if they say it's HEVX/x265, it might be a sane file size
      from: title
    content_filter:
      reject:
        - '*.ISO'
        - '*.iso'
        - '*.exe'
        - '*.EXE'
    deluge:
      path: /home/user/Downloads
      #move_completed_path:  /home/user/Downloads/finished # Handled by movefinished.yaml now
      label: anime
      ratio: 1.5
      remove_at_ratio: yes
      magnetization_timeout: 30

  animeerairaws:
    quality: 720p
    accept_all: yes
    deluge:
      path: /home/user/Downloads
      #move_completed_path:  /home/user/Downloads/finished # Handled by movefinished.yaml now
      label: anime
      ratio: 1.5
      remove_at_ratio: yes
      magnetization_timeout: 30

  animehorriblesubs:
    accept_all: yes
    deluge:
      path: /home/user/Downloads
      #move_completed_path:  /home/user/Downloads/finished # Handled by movefinished.yaml now
      label: anime
      ratio: 1.5
      remove_at_ratio: yes
      magnetization_timeout: 30

tasks:
  # RIP: Fall 2020
  # animedl-HorribleSubs:
  #   rss:
  #     url: http://horriblesubs.info/rss.php?res=720
  #     ascii: yes
  #     all_entries: no
  #   template: animehorriblesubs
  animedl-erairaws:
    rss:
      url: https://www.erai-rss.info/rss-all/
      ascii: yes
      all_entries: no
    template: animeerairaws
  animedl-nyaa:
    rss:
      url: https://nyaa.si/?page=rss&c=1_2&f=0
      ascii: yes
      all_entries: no
    template: anime_regexp
  animedl-animetosho:
    rss:
      url: https://feed.animetosho.org/rss2?only_tor=1
      ascii: yes
      all_entries: no
    template: anime_regexp
  animedl-tokyotosho:
    rss:
      url: https://www.tokyotosho.info/rss.php?filter=1%2C11%2C5
      ascii: yes
      all_entries: no
    template: anime_regexp
  animedl-minglong:
    rss:
      url: http://tracker.minglong.org/rss.xml
      ascii: yes
      all_entries: no
    template: anime_regexp
  animedl-acgnx:
    rss:
      url: https://www.acgnx.se/rss-sort-2.xml
      ascii: yes
      all_entries: no
    template: anime_regexp
  # This is done primarily as a task to get data from deluge because content_size doesn't work on magnets well during initial filtering
  pause_large_torrents:
    sleep:
      seconds: 60 # This should give enough time for most of the torrents/magnets to start and get sizes etc.
    from_deluge: yes
    disable: [seen, seen_info_hash]
    # Pause all torrents larger then 30GB that do not have the label "largeanimeok", Note Deluge labels are always lowercase in flexget
    # And I don't want to deal with some of the stupidly large torrents people post that I either end up downloading (and then deleting)
    # or chew up my Seedbox bandwith
    if:
      - deluge_label != "largeanimeok" and content_size >= 30720 : accept
    deluge:
      action: pause

schedules:
  - tasks: '*'
    interval:
      hours: 1